/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oopca1;

/**
 *
 * @author Joe Grace
 * x22448734
 */
public class SurveyJframe extends javax.swing.JFrame {

    /**
     * Creates new form SurveyJframe
     */
    public SurveyJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNSubmit = new javax.swing.JButton();
        BTNReset = new javax.swing.JButton();
        BTNClose = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        CBProvider = new javax.swing.JComboBox<>();
        CBHouseType = new javax.swing.JComboBox<>();
        CBHeatMeth = new javax.swing.JComboBox<>();
        LBLDemo = new javax.swing.JLabel();
        LBLBill = new javax.swing.JLabel();
        TFBill = new javax.swing.JTextField();
        CBAgeGroup = new javax.swing.JComboBox<>();
        CBFuelType = new javax.swing.JComboBox<>();
        LBLConsumptionHabbits1 = new javax.swing.JLabel();
        CBTransportaion = new javax.swing.JComboBox<>();
        CBLocation = new javax.swing.JComboBox<>();
        SurveyTitle = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        TARenewableEnergyQ2 = new javax.swing.JTextArea();
        LBLFuturePlans = new javax.swing.JLabel();
        LBLRenewableEnergyQ2 = new javax.swing.JLabel();
        CBInsulationType = new javax.swing.JComboBox<>();
        LBLDemo1 = new javax.swing.JLabel();
        LBLGovernmentIncentiveQ1 = new javax.swing.JLabel();
        LBLRenewableEnergyQ = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TARenewableEnergyQ1 = new javax.swing.JTextArea();
        LBLGovernmentIncentiveQ = new javax.swing.JLabel();
        LBLRenewableEnergyQ1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TARenewableEnergyQ1 = new javax.swing.JTextArea();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        textField1 = new java.awt.TextField();
        textArea1 = new java.awt.TextArea();
        BTNClickMe = new java.awt.Button();
        textArea2 = new java.awt.TextArea();
        LBLValidationResult = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));

        BTNSubmit.setText("Submit");
        BTNSubmit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSubmitActionPerformed(evt);
            }
        });

        BTNReset.setText("Reset");
        BTNReset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNResetActionPerformed(evt);
            }
        });

        BTNClose.setText("Close");
        BTNClose.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCloseActionPerformed(evt);
            }
        });

        CBProvider.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electricity Provider", "Bord Gás Energy", "Electric Ireland", "PrePay Power", "SSE Electricity", "Energia" }));

        CBHouseType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Type of Residence", "House", "Apartment", "Other" }));

        CBHeatMeth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Heating Method", "Gas", "Oil", "Electric", "Renewable" }));

        LBLDemo.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        LBLDemo.setText("Demographic");

        LBLBill.setText("Monthy Electricity Bill");

        TFBill.setText("0");

        CBAgeGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Age Group", "18-25", "25-36", "36-50", "50 +" }));
        CBAgeGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBAgeGroupActionPerformed(evt);
            }
        });

        CBFuelType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transportaion Fuel Type", "Petrol", "Diesel", "Electric", "None" }));

        LBLConsumptionHabbits1.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        LBLConsumptionHabbits1.setText("Consumption Habbits");

        CBTransportaion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transportaion", "Car", "Bicycle", "Motorbike", "Public Transport", "Walk" }));

        CBLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "County", "Antrim", "Armagh", "Carlow", "Cavan", "Clare", "Cork", "Derry", "Donegal", "Down", "Dublin", "Fermanagh", "Galway", "Kerry", "Kildare", "Kilkenny", "Laois", "Leitrim", "Limerick", "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly", "Roscommon", "Sligo", "Tipperary", "Tyrone", "Waterford", "Westmeath", "Wexford", "Wicklow" }));
        CBLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBLocationActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(CBProvider, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CBHouseType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CBHeatMeth, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LBLDemo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LBLBill, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(TFBill, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CBAgeGroup, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CBFuelType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LBLConsumptionHabbits1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CBTransportaion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CBLocation, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBAgeGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBHouseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(CBProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBTransportaion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLConsumptionHabbits1)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                            .addComponent(LBLBill)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TFBill, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addComponent(CBHeatMeth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CBAgeGroup, CBFuelType, CBHeatMeth, CBHouseType, CBLocation, CBProvider, CBTransportaion});

        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(LBLDemo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBAgeGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBHouseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(LBLConsumptionHabbits1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLBill)
                    .addComponent(TFBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBHeatMeth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBTransportaion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        SurveyTitle.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        SurveyTitle.setText("Energy Survey");
        SurveyTitle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        TARenewableEnergyQ2.setColumns(20);
        TARenewableEnergyQ2.setRows(5);
        jScrollPane3.setViewportView(TARenewableEnergyQ2);

        LBLFuturePlans.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        LBLFuturePlans.setText("Future Plans");

        LBLRenewableEnergyQ2.setText("efficiency in your home? How?");

        CBInsulationType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Insulation Type", "External Wall Insulation", "Cavity Wall Insulation", "Internal Wall insulation" }));

        LBLDemo1.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        LBLDemo1.setText("Cost Savings measures");

        LBLGovernmentIncentiveQ1.setText("incentives to do so?");

        LBLRenewableEnergyQ.setText("Do you use any form of renewable energy?");

        TARenewableEnergyQ1.setColumns(20);
        TARenewableEnergyQ1.setRows(5);
        jScrollPane2.setViewportView(TARenewableEnergyQ1);

        LBLGovernmentIncentiveQ.setText("Are you aware of any government ");

        LBLRenewableEnergyQ1.setText("Do you plan on Improving energy");

        TARenewableEnergyQ1.setColumns(20);
        TARenewableEnergyQ1.setRows(5);
        jScrollPane2.setViewportView(TARenewableEnergyQ1);

        jDesktopPane2.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(LBLFuturePlans, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(LBLRenewableEnergyQ2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(CBInsulationType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(LBLDemo1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(LBLGovernmentIncentiveQ1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(LBLRenewableEnergyQ, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(LBLGovernmentIncentiveQ, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(LBLRenewableEnergyQ1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLGovernmentIncentiveQ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(LBLGovernmentIncentiveQ)
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addComponent(LBLRenewableEnergyQ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLFuturePlans)
                            .addComponent(CBInsulationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLDemo1)
                            .addComponent(LBLRenewableEnergyQ)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLRenewableEnergyQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLDemo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBInsulationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBLRenewableEnergyQ)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LBLFuturePlans)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LBLRenewableEnergyQ1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBLRenewableEnergyQ2)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(LBLGovernmentIncentiveQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBLGovernmentIncentiveQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        textField1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textField1.setText("Get  A  Quote");

        textArea1.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 3, 14)); // NOI18N
        textArea1.setText("Thinking of switching to \nsolar energy? \nuse our free calculator to\n see how much you could save.");

        BTNClickMe.setLabel("CLICK ME");
        BTNClickMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNClickMeActionPerformed(evt);
            }
        });

        textArea2.setFont(new java.awt.Font("Adobe Caslon Pro", 1, 14)); // NOI18N
        textArea2.setText("To get figures on solar energy production \nand cost it is best to consult professional\ns but his calculator will give you an idea if\n it the the right choice for you. you ca\nn find the price of panels on sites such\n as www.solarstore.ie. ");

        jDesktopPane3.setLayer(textField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(textArea1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(BTNClickMe, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(textArea2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BTNClickMe, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(textArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(BTNClickMe, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNClose, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SurveyTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDesktopPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBLValidationResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(104, 104, 104)))))
                .addGap(26, 26, 26)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BTNClose, BTNReset, BTNSubmit});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SurveyTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBLValidationResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTNSubmit)
                            .addComponent(BTNReset)
                            .addComponent(BTNClose)))
                    .addComponent(jDesktopPane2)
                    .addComponent(jDesktopPane3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSubmitActionPerformed
        SurveyValidation myValidator = new SurveyValidation();
        double monthlyBill = Double.parseDouble(TFBill.getText());
        myValidator.setMonthlyElectricityBill(monthlyBill);
        String validationResult = myValidator.validateAll();
        LBLValidationResult.setText(validationResult);
    }//GEN-LAST:event_BTNSubmitActionPerformed

    private void BTNResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNResetActionPerformed
        TARenewableEnergyQ1.setText("");    
        TARenewableEnergyQ2.setText("");
        TFBill.setText("0");
        jTextArea1.setText("");
        


// TODO add your handling code here:
    }//GEN-LAST:event_BTNResetActionPerformed

    private void BTNCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCloseActionPerformed
        setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_BTNCloseActionPerformed

    private void CBAgeGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBAgeGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBAgeGroupActionPerformed

    private void CBLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBLocationActionPerformed

    private void BTNClickMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNClickMeActionPerformed
        EnergyCostSavings myEnergyCostSavings = new EnergyCostSavings();
        myEnergyCostSavings.setVisible(true); 
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_BTNClickMeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SurveyJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SurveyJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SurveyJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SurveyJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SurveyJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BTNClickMe;
    private javax.swing.JButton BTNClose;
    private javax.swing.JButton BTNReset;
    private javax.swing.JButton BTNSubmit;
    private javax.swing.JComboBox<String> CBAgeGroup;
    private javax.swing.JComboBox<String> CBFuelType;
    private javax.swing.JComboBox<String> CBHeatMeth;
    private javax.swing.JComboBox<String> CBHouseType;
    private javax.swing.JComboBox<String> CBInsulationType;
    private javax.swing.JComboBox<String> CBLocation;
    private javax.swing.JComboBox<String> CBProvider;
    private javax.swing.JComboBox<String> CBTransportaion;
    private javax.swing.JLabel LBLBill;
    private javax.swing.JLabel LBLConsumptionHabbits1;
    private javax.swing.JLabel LBLDemo;
    private javax.swing.JLabel LBLDemo1;
    private javax.swing.JLabel LBLFuturePlans;
    private javax.swing.JLabel LBLGovernmentIncentiveQ;
    private javax.swing.JLabel LBLGovernmentIncentiveQ1;
    private javax.swing.JLabel LBLRenewableEnergyQ;
    private javax.swing.JLabel LBLRenewableEnergyQ1;
    private javax.swing.JLabel LBLRenewableEnergyQ2;
    private java.awt.Label LBLValidationResult;
    private javax.swing.JLabel SurveyTitle;
    private javax.swing.JTextArea TARenewableEnergyQ1;
    private javax.swing.JTextArea TARenewableEnergyQ2;
    private javax.swing.JTextField TFBill;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private java.awt.TextArea textArea1;
    private java.awt.TextArea textArea2;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
